warpscroll/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from rest_framework.authtoken.views import obtain_auth_token

from travel_planner import api_views
from travel_planner.views import home, save_trip, add_trip, remove_trip, ajax_login, ajax_change_password

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^save-trip/$', save_trip, name='save_trip'),
    url(r'^add-trip/$', add_trip, name='add_trip'),
    url(r'^remove-trip/$', remove_trip, name='remove_trip'),
    url(r'^login/$', ajax_login, name='login'),
    url(r'^change_password/$', ajax_change_password, name='change_user_password'),
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include(api_views.router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api-token-auth/', obtain_auth_token),
]

travel_planner/models.py
import uuid
from datetime import date, timedelta, datetime
from dateutil.relativedelta import relativedelta
from dateutil.tz import tzoffset
from django.contrib.auth.models import User
from django.db import models


def _days_left(start_date, timezone=None):
    if not start_date:
        return
    if timezone:
        today = datetime.now(tz=tzoffset("user", timezone)).date()
    else:
        today = date.today()
    positive = start_date - today > timedelta()
    if positive:
        relative_date = relativedelta(start_date, today)
        years, months, days = relative_date.years, relative_date.months, relative_date.days
        for caption, item in (("year", years), ("month", months), ("day", days)):
            if item:
                yield "{} {}".format(item, caption)
                if item > 1:
                    yield "s"
                yield " "


class Trip(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    destination = models.CharField(blank=True, max_length=200)
    start_date = models.DateField(blank=True, null=True)
    end_date = models.DateField(blank=True, null=True)
    comment = models.TextField(blank=True)
    view_only_token = models.UUIDField(default=uuid.uuid4)

    def __str__(self):
        return self.destination

    def days_left(self, timezone=None):
        days_left_value = "".join(_days_left(self.start_date, timezone))
        if days_left_value:
            days_left_value += " until trip"
        return days_left_value

travel_planner/views.py
from datetime import date, datetime

from dateutil.tz import tzoffset
from django.contrib.auth import login
from django.contrib.auth.forms import AuthenticationForm
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseNotFound, HttpResponseBadRequest
from django.http import JsonResponse
from django.shortcuts import render, redirect

from travel_planner.models import Trip


def home(request):
    if request.user.is_anonymous:
        return render(
            request,
            "homepage.html"
        )
    else:
        if request.session.get("time_zone"):
            time_zone = request.session.get("time_zone") * 60 * 60
            today = datetime.now(tz=tzoffset("user", time_zone)).date()
        else:
            today = date.today()
        return render(
            request,
            "homepage.html", {
                "user": request.user,
                "current_trips": Trip.objects.filter(
                    owner=request.user,
                    start_date__lte=today,
                    end_date__gte=today
                ).order_by("start_date", "-id"),
                "upcoming_trips": Trip.objects.filter(
                    owner=request.user,
                    start_date__gt=today
                ).order_by("start_date", "-id"),
                "past_trips": Trip.objects.filter(
                    owner=request.user,
                    end_date__lt=today
                ).order_by("start_date", "-id"),
                "current_day": today
            }
        )


def convert_date(date_string):
    if date_string:
        return datetime.strptime(date_string, "%b. %d, %Y")


def save_trip(request):
    trip_id = request.POST.get("trip-id")
    trip = Trip.objects.get(id=trip_id)
    if not trip:
        return HttpResponseNotFound('<h1>Trip not found</h1>')
    if trip.owner != request.user:
        raise PermissionDenied
    if request.POST.get("delete"):
        return remove_trip(request, trip)
    trip.destination = request.POST.get("destination")
    trip.start_date = convert_date(request.POST.get("start_date"))
    if not request.POST.get("end_date"):
        trip.end_date = trip.start_date
    else:
        trip.end_date = convert_date(request.POST.get("end_date"))
    trip.comment = request.POST.get("comment")
    trip.save()
    return redirect('home')


def add_trip(request):
    if request.user.is_anonymous:
        return HttpResponseBadRequest('<h1>Must be logged in</h1>')
    trip = Trip()
    trip.owner = request.user
    trip.start_date = datetime.now()
    trip.end_date = datetime.now()
    trip.save()
    return redirect('home')


def remove_trip(request, trip):
    trip.delete()
    return redirect('home')


def ajax_login(request):
    if request.POST.get("time_zone"):
        request.session['time_zone'] = int(request.POST.get("time_zone"))
    form = AuthenticationForm(request, data=request.POST)
    if form.is_valid():
        login(request, form.get_user())
        return JsonResponse({
            "OK": True,
            "admin": form.get_user().is_staff
        })
    else:
        return HttpResponseBadRequest("Incorrect username or password")


def ajax_change_password(request):
    old_password = request.POST.get("old_password")
    new_password = request.POST.get("new_password")
    confirm_password = request.POST.get("confirm_password")
    if not request.user.check_password(old_password):
        return HttpResponseBadRequest('Original password not correct')
    elif not new_password:
        return HttpResponseBadRequest('New password must not be blank')
    elif new_password != confirm_password:
        return HttpResponseBadRequest("New password doesn't match")
    else:
        request.user.set_password(new_password)
        request.user.save()
        login(request, request.user)
        return JsonResponse({"OK": True})

travel_planner/templates/add_destination.html
<form action="{% url 'add_trip' %}" method="post" style="display: inline;">
    {% csrf_token %}
    <input type="submit" name="save" class="btn btn-outline-warning btn-sm add-dest"
           value="Add destination"/>
</form>

travel_planner/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <meta name="description" content="">

    <title>{% block title %}{% endblock %}</title>

    <link href="{% static "bootstrap/css/bootstrap.css" %}" rel="stylesheet">
    <link href="{% static "travel_planner/style.css" %}" rel="stylesheet">
</head>

<body>
{% block content %}{% endblock %}

{% include 'javascript_tags.html' %}
</body>
</html>

travel_planner/templates/filter-bar.html
<nav class="navbar navbar-light filter-bar">
    <ul class="nav navbar-nav">
        <li class="nav-item active">
            <a class="nav-link show-all" href="#">Show all</a>
        </li>
        <li class="nav-item">
            <a class="nav-link next-month" href="#">Through next month</a>
        </li>
        <li class="nav-item">
            <a class="nav-link next-year" href="#">Through next year</a>
        </li>
        <li class="nav-item">
            <a class="nav-link past" href="#">Past</a>
        </li>
    </ul>
    <form class="form-inline pull-xs-right">
        <input class="form-control search-destinations" type="text" placeholder="Search destinations">
        <button class="btn btn-outline-success search-destinations-button" type="submit">Search</button>
    </form>
</nav>

travel_planner/templates/homepage.html
{% extends "base.html" %}
{% block title %}Warpscroll: plan your trip through anywhere.{% endblock %}
{% block content %}
    {% with col_style="col-md-8 offset-md-2" %}
        <div class="container-fluid">
            <div class="row header-section">
                <div class="{{ col_style }}">
                    <div class="body-text page-section">

                        <h2>Warp Scroll</h2>

                        <h4>Plan your trip through anything.</h4>
                    </div>
                </div>
                <div class="{{ col_style }}">
                    <div class="body-text page-section">

                        {% include "registration_form.html" %}
                    </div>
                </div>
            </div>
            <div class="row">
                <div id="admin-area" style="display: none;">
                    <div id="admin-user-area"></div>
                    <div id="admin-trips-area"></div>
                </div>
            </div>
            <div class="row">
                <div class="{{ col_style }}">
                    <div id="trip-list" style="{% if user.is_anonymous %}display: none;{% endif %}">
                        {% include 'filter-bar.html' %}
                        <div style="float: right;" class="mini-action-bar">
                            {% include 'add_destination.html' %}
                            <a href="" class="btn btn-outline-info btn-sm print-plan">Print travel plan for
                                next
                                month</a>
                        </div>
                        {% include "trip_list.html" with trips=current_trips title="Current Trips" class="current-trips" %}
                        {% include "trip_list.html" with trips=upcoming_trips title="Upcoming Trips" upcoming=True class="upcoming-trips" %}
                        {% include "trip_list.html" with trips=past_trips title="Past Trips" class="past-trips" %}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="{{ col_style }}" style="margin-bottom: 20px;" id="next-prev-page">
                    <a href="" class='prev-page' style="visibility: hidden;">Previous Trips</a>
                    <a href="" class='next-page' style="visibility: hidden;">Next Trips</a>
                </div>
            </div>
        </div>
    {% endwith %}
{% endblock %}

travel_planner/templates/javascript_tags.html
{% load static %}
<link rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/css/bootstrap-datepicker.css"
      integrity="sha256-8qbGU+6CyzZndATqt8JYzpha71ptNqBkpagFVI+t6oI=" crossorigin="anonymous"/>
{% if debug %}
    {# jQuery #}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    {# Date picker #}
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/js/bootstrap-datepicker.js"
            crossorigin="anonymous"></script>
    {# Underscore and Backbone #}
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/backbone.js/1.3.3/backbone.js"
            crossorigin="anonymous"></script>
{% else %}
    {# jQuery #}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    {# Date picker #}
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/js/bootstrap-datepicker.min.js"
            integrity="sha256-urCxMaTtyuE8UK5XeVYuQbm/MhnXflqZ/B9AOkyTguo=" crossorigin="anonymous"></script>
    {# Underscore and Backbone #}
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js"
            integrity="sha256-obZACiHd7gkOk9iIL/pimWMTJ4W/pBsKu+oZnSeBIek=" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/backbone.js/1.3.3/backbone-min.js"
            integrity="sha256-0atoj6xVOJUoBM8Vp5PFywwLLE+aNl2svi4Q9UWZ+dQ=" crossorigin="anonymous"></script>
{% endif %}
<script type="text/template" id="trip-card-template">
    <div class="card trip-card">
        <h3 class="card-header">
            <input type="text" style="width: 100%" title="Destination" placeholder="Destination" name="destination"
                   value="<%- destination %>">
        </h3>
        <div class="card-block">
            <p class="card-text">
                <input type="text" name="start_date" value="<%- start_date %>" title="start date"
                       class="edit-start-date datepicker" data-date-format="yyyy-m-dd">
                -
                <input type="text" name="end_date" class="edit-end-date datepicker" value="<%- end_date %>"
                       title="end date" data-date-format="yyyy-m-dd">
                <span class="date-switched-messages" role="alert"></span>

                <span class="tag tag-default tag-pill days-left-tag"><%- days_left %></span>

                <input type="submit" name="save" class="btn btn-outline-danger btn-sm pull-xs-right remove-dest"
                       value="Remove">
                <input type="submit" name="save" class="btn btn-outline-info btn-sm pull-xs-right save-dest"
                       value="Save" style="display: none;">
            </p>
        </div>
        <textarea class="trip-description" title="trip description"
                  placeholder="Trip comments" name="comment"><%- comment %></textarea>
    </div>
</script>
<script type="text/template" id="admin-users-template">
    <h2>Users</h2>
    <table>
        <tbody>
        <% _.each(users, function (user) { %>
        <tr>
            <td class="user-id"><%- user.id %></td>
            <td class="username"><input type="text" value="<%- user.username %>" title="username"/></td>
            <td><a href="" class="btn btn-outline-secondary btn-sm admin-update-user">save</a></td>
            <td><a href="" class="btn btn-outline-danger btn-sm admin-delete-user">delete</a></td>
        </tr>
        <% }); %>
        </tbody>
    </table>
</script>
<script type="text/template" id="admin-trips-template">
    <h2>Trips</h2>
    <table>
        <tbody>
        <% _.each(trips, function (trip) { %>
        <tr>
            <td class="trip-id"><%- trip.id %></td>
            <td><%- trip.owner %></td>
            <td class="destination"><input type="text" value="<%- trip.destination %>" title="destination"/></td>
            <td><%- trip.start_date %></td>
            <td><%- trip.end_date %></td>
            <td><%- trip.comment %></td>
            <td><a href="" class="btn btn-outline-secondary btn-sm admin-update-trip">save</a></td>
            <td><a href="" class="btn btn-outline-danger btn-sm admin-delete-trip">delete</a></td>
        </tr>
        <% }); %>
        </tbody>
    </table>
</script>
<script src="{% static 'travel_planner/script.js' %}"></script>

travel_planner/templates/registration_form.html
<div class="row" id="login-menu" style="{% if not request.user.is_anonymous %}display: none;{% endif %}">
    <div class="col-md-6">
        <h5>Login</h5>
        <form method="post" action="{% url 'rest_framework:login' %}?next=/" id="login-form">
            <input type="hidden" id="ajax_login" value="{% url 'login' %}"/>
            {% csrf_token %}
            <div class="form-group">
                <label>Username:
                    <input class="form-control" type="text" name="username" required>
                </label>
            </div>
            <div class="form-group">
                <label>Password:
                    <input class="form-control" type="password" name="password" required>
                </label>
            </div>
            <div class="alert alert-danger login-error-message" role="alert" style="display: none;"></div>
            <input class="btn btn-outline-primary" type="submit" value="Login"/>
        </form>
    </div>
    <div class="col-md-6">
        <h5 class="register">Register</h5>
        <form method="post" action="{% url 'user-list' %}?next=/" id="register-form">
            {% csrf_token %}
            <div class="form-group">
                <label>Username:
                    <input class="form-control" type="text" name="username" required>
                </label>
            </div>
            <div class="form-group">
                <label>Password:
                    <input class="form-control" type="password" name="password" required>
                </label>
                <label>
                    <input class="form-control" type="password" name="password-confirm"
                           placeholder="Confirm password" required>
                </label>
            </div>
            <div class="alert alert-danger register-error-message" role="alert" style="display: none;"></div>
            <input class="btn btn-outline-primary" type="submit" value="Register"/>
        </form>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div style="{% if request.user.is_anonymous %}display: none;{% endif %}" id="user-info">
            <span style="margin-right: 10px" id="username-field">{{ user.username }}</span>
            <a class="btn btn-outline-secondary admin-button" style="display: none"
               href="{% url 'admin:index' %}">Admin</a>
            <a class="btn btn-outline-secondary change-password-button"
               href="?next=/">Change Password</a>
            <a class="btn btn-outline-secondary logout-button"
               href="{% url 'rest_framework:logout' %}?next=/">Logout</a>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div style="display: none;" id="change-user-password">
            <h5 class="register">Change password</h5>
            <form method="post" action="{% url 'change_user_password' %}?next=/" id="change-user-password-form">
                {% csrf_token %}
                <div class="form-group">
                    <label>Old Password:
                        <input class="form-control" type="password" name="old-password" required>
                    </label>
                </div>
                <div class="form-group">
                    <label>New Password:
                        <input class="form-control" type="password" name="password" required>
                    </label>
                    <label>
                        <input class="form-control" type="password" name="password-confirm"
                               placeholder="Confirm password" required>
                    </label>
                </div>
                <div class="alert alert-danger register-error-message" role="alert" style="display: none;"></div>
                <input class="btn btn-outline-primary" type="submit" value="Change password"/>
            </form>
        </div>
    </div>
</div>

travel_planner/templates/trip_list.html
<h3>{{ title }}</h3>
<div class="trip-section {{ class }}">
{% for trip in trips %}
    <div class="card trip-card">
        <form method="post" action="{% url 'save_trip' %}">
            {% csrf_token %}
            <input type="hidden" name="trip-id" value="{{ trip.id }}"/>
            <h3 class="card-header">
                <input type="text" style="width: 100%" title="Destination" placeholder="Destination"
                       name="destination"
                        {% if trip.destination %}
                       value="{{ trip.destination }}"
                        {% endif %}
                />
            </h3>
            <div class="card-block">
                <p class="card-text">
                    <input type="text" name="start_date" value="{{ trip.start_date }}"
                           title="start date" class="edit-start-date datepicker" data-date-format="M. d, yyyy">
                    -
                    <input type="text" name="end-date" class="edit-end-date datepicker"
                           value="{% if trip.end_date > trip.start_date %}{{ trip.end_date }}{% endif %}"
                           title="end date" data-date-format="M. d, yyyy">
                    {% if trip.days_left %}
                        <span class="tag tag-default tag-pill">
                        {{ trip.days_left }}
                    </span>
                    {% endif %}
                    <input type="submit" name="delete" class="btn btn-outline-danger btn-sm pull-xs-right remove-dest"
                           value="Remove"/>
                    <input type="submit" name="save" class="btn btn-outline-info btn-sm pull-xs-right save-dest"
                           value="Save"/>
                </p>
            </div>
            <textarea class="trip-description" title="trip description" placeholder="Trip comments"
                      name="comment">{{ trip.comment.strip }}</textarea>
        </form>
    </div>
{% endfor %}
</div>